#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m 1 &
~/bin/start.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          36
bspc config top_padding          0

bspc config split_ratio          0.55
bspc config borderless_monocle   true 
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# rules
bspc rule -a Pavucontrol state=floating

polybar main &
