#! /bin/sh

./.config/polybar/launch.sh
compton &
wal -i ~/wal &

if ! ps -A | grep 'redshift' ; then
    redshift &
fi

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding          0

bspc config split_ratio          0.55
bspc config borderless_monocle   false 
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# rules
bspc rule -a Pavucontrol state=floating
bspc rule -a Termite state=pseudo_tiled
#bspc rule -a kitty state=pseudo_tiled
