#!/bin/bash

# pgrep -x sxhkd > /dev/null || sxhkd -m 1 -c $HOME/.config/berry/sxhkdrc &
sxhkd -c $HOME/.config/berry/sxhkdrc &
~/bin/start.sh

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 0
berryc title_height       16
berryc top_gap            24
berryc edge_gap     48 24 24 24

# Set decoration colors
berryc focus_color         24283b
berryc unfocus_color       24283b
berryc inner_focus_color   414868
berryc inner_unfocus_color 1D202F

# Other options
berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "true"
